### ISSUE TITLE
Does it have to be ID?

### ISSUE THREAD

**Issue by emage** [joshgillies/text-overflow-clamp#2]
It doesn't seem to work when  I have more than one IDs of 'js-toclamp' that needs to be clamped.
I tried to make it class by changing the getElementById to getElementsByClassName but still does not work.

- not a coder, just following the code pen example to use on my site.

**Comment by joshgillies** [comment]
Hey @emage, for sure this will work with classes rather than ids. The thing to note here though is if you're using `getElementsByClassName` which returns a list of elements, and the library only accepts a single element to act on. As this isn't my library but just a npm packaged fork of the original http://codepen.io/Merri/pen/Dsuim I'm hesitant to make too many changes to the inner workings. For now you could do something like:

```js
var clamp = require('text-overflow-clamp');
[...document.getElementsByClassName('js-toclamp')].forEach((element) => clamp(element, 3));
```
